name: Génrérer JAR et déployer en prod

on:
  push:
    branches:
      - main

env:
  MAVEN_OPTS: "-Dmaven.repo.local=/chemin/vers/conteneur/des/dépendances"

jobs:
  build:
    name: Build de l'application
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@main
    - name: Set up JDK 17
      uses: actions/setup-java@v4.5.0
      with:
        java-version: '17'
        distribution: zulu

    - name: Package le projet
      run: mvn clean package -DskipTests

    - name: Mettre les dépendences en cache
      uses: actions/cache@v4.1.2
      with:
        path: $MAVEN_OPTS
        key: librairies

  test:
    runs-on: ubuntu-latest
    needs: build
    name: Lance les tests unitaires

    steps:
      - uses: actions/checkout@master
      - name: Set up JDK 17
        uses: actions/setup-java@v4.5.0
        with:
          java-version: '17'
          distribution: zulu
      - run: mvn test
